### PR TITLE
Fix for static-quantization

### PR DESCRIPTION
**Pull request by AlexeyAB**
@rwightman Hi,

Some fixes for static-quantization of EfficientNet-Lite:

1. Use `nn.Conv2d` instead of `F.conv2d` for Conv2dSameExport

2. Use `nn.quantized.FloatFunctional instead` of `+=` for Residual connections

3. There is still only 1 issue with `nn.ZeroPad2d`: https://colab.research.google.com/gist/AlexeyAB/820648ce1e6a8ae25ea5bdb49a0c7a81/pytorch_quant_pad_same.ipynb
    https://github.com/rwightman/gen-efficientnet-pytorch/blob/e84f5546ceb5be79a13d86209ecc93077f264057/geffnet/conv2d_layers.py#L110

    * Do you know simple solution for this issue?
    * Can I just comment this line `x = self.pad(x)` in my local copy if I use network resolution that is multiple of 32 = (2^5) for example 224x224 for models with 5 subsampling layers?

### CODE REVIEW

**Comment by AlexeyAB** [comment]
It seems with these changes the pre-trained weights cannot be loaded: https://colab.research.google.com/gist/AlexeyAB/4e9bd9f92d8e6faf4769ed7b4ca42d1e/pytorch_quant_pad_same.ipynb

```
/root/.cache/torch/hub/AlexeyAB_gen-efficientnet-pytorch_quantization/geffnet/gen_efficientnet.py in _create_model(model_kwargs, variant, pretrained)
    288     model = GenEfficientNet(**model_kwargs)
    289     if pretrained:
--> 290         load_pretrained(model, model_urls[variant])
    291     if as_sequential:
    292         model = model.as_sequential()

/root/.cache/torch/hub/AlexeyAB_gen-efficientnet-pytorch_quantization/geffnet/helpers.py in load_pretrained(model, url, filter_fn, strict)
     41     input_conv = 'conv_stem'
     42     classifier = 'classifier'
---> 43     in_chans = getattr(model, input_conv).weight.shape[1]
     44     num_classes = getattr(model, classifier).weight.shape[0]
     45 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    777                 return modules[name]
    778         raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
--> 779             type(self).__name__, name))
    780 
    781     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

ModuleAttributeError: 'Conv2dSameExport' object has no attribute 'weight'
```

**Comment by rwightman** [comment]
@AlexeyAB hmm, I'm not too inclined to change the base models for quantization support. Overall there has to be a better solution than the current PyTorch post-train static quantization. It's just so clunky. Is the current level of changes even enough to get optimal performance? A lot of the torchvision and other examples I've seen define op fusions, etc and basically end up being requiring parallel block definitions that inherit from the original def...

**Comment by AlexeyAB** [comment]
@rwightman I use: eval -> fusion (conv+bn+relu) -> static-quantization for qnnpack (prepare, callibraton, converting) -> tracing.

Usually quantization is applied to small models for use on mobile devices like Android/iOS by using Pytorch-mobile (if we use Pytorch). But I get lower speed and slightly higher accuracy by using int8 quantization than without it on Android, which is strange: https://github.com/pytorch/pytorch/issues/44782#issuecomment-699713989

> etc and basically end up being requiring parallel block definitions that inherit from the original def...

Do you mean something like this? https://discuss.pytorch.org/t/how-can-l-run-two-blocks-in-parallel/61618/3?u=mdc

**Comment by AlexeyAB** [comment]
I will close this PR. 

* Better to convert Pytorch model to TFlite and use TFlite graph mode quantization 
* Or wait for the implementation of the graph mode quantization in Pytorch

**Pull request closed without merging**
